import { GPIOPinState, type Simulator } from 'rp2040js';

export type ServoSignal =
  | { kind: 'missing'; commandRad: number }
  | { kind: 'valid'; commandRad: number; pulseUs: number; periodUs: number; atUs: number }
  | { kind: 'lost'; commandRad: number; atUs: number };

/** Decode the configured 50 Hz, 1000–2000 us servo interface from pin edges.
 * Missing/invalid input holds the last target (an explicit actuator assumption,
 * not a claim that every physical servo has the same signal-loss behaviour).
 */
export class ServoPulseDecoder {
  private rise: { kind: 'none' } | { kind: 'edge'; atUs: number; periodUs: number } = { kind: 'none' };
  private accepted: { kind: 'none' } | { kind: 'pulse'; atUs: number; pulseUs: number; periodUs: number } = { kind: 'none' };
  edge(high: boolean, nowUs: number): void {
    if (high) {
      this.rise = { kind: 'edge', atUs: nowUs, periodUs: this.rise.kind === 'edge' ? nowUs - this.rise.atUs : 0 };
      return;
    }
    if (this.rise.kind !== 'edge') return;
    const pulseUs = nowUs - this.rise.atUs;
    const periodUs = this.rise.periodUs;
    if (pulseUs >= 990 && pulseUs <= 2010 && periodUs >= 19000 && periodUs <= 21000) {
      this.accepted = { kind: 'pulse', atUs: nowUs, pulseUs, periodUs };
    }
  }
  sample(nowUs: number): ServoSignal {
    if (this.accepted.kind === 'none') return { kind: 'missing', commandRad: 0 };
    const { pulseUs, periodUs, atUs } = this.accepted;
    const commandRad = (Math.max(1000, Math.min(2000, pulseUs)) - 1500) / 500 * (10 * Math.PI / 180);
    return nowUs - atUs > 60000
      ? { kind: 'lost', commandRad, atUs }
      : { kind: 'valid', commandRad, pulseUs, periodUs, atUs };
  }
}

/** Observe GPIO mux/output edges generated by rp2040js, never PWM CC registers. */
export function attachServoPwm(simulator: Simulator): { elevator: ServoPulseDecoder; rudder: ServoPulseDecoder } {
  const elevator = new ServoPulseDecoder();
  const rudder = new ServoPulseDecoder();
  for (const [index, decoder] of [[16, elevator], [17, rudder]] as const) {
    const pin = simulator.rp2040.gpio[index];
    if (!pin) throw new Error(`missing servo GPIO ${index}`);
    pin.addListener(state => {
      if (state === GPIOPinState.High || state === GPIOPinState.Low) decoder.edge(state === GPIOPinState.High, simulator.clock.micros);
    });
  }
  return { elevator, rudder };
}
